<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
    
    //'vendor/ircmaxell/password-compat/lib/password.php',
    //'vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php',
    //'vendor/swiftmailer/swiftmailer/lib/swift_required.php',
    //'vendor/swiftmailer/swiftmailer/lib/classes/Swift.php',
    //'vendor/laravel/framework/src/Illuminate/Session/SessionInterface.php',
    //'vendor/laravel/framework/src/Illuminate/Auth/UserInterface.php',
    //'vendor/laravel/framework/src/Illuminate/Auth/Reminders/RemindableInterface.php',
    //'vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup.php',
    'vendor/laravel/framework/src/Illuminate/Support/Collection.php',
    'vendor/symfony/finder/Symfony/Component/Finder/Finder.php',
    
    'vendor/laravel/framework/src/Illuminate/Database/Connection.php',
    'vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php',
    'vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php',
    'vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Grammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php',
    
    'vendor/symfony/security-core/Symfony/Component/Security/Core/Util/SecureRandom.php',
    'vendor/symfony/security-core/Symfony/Component/Security/Core/Util/SecureRandomInterface.php',
    'vendor/symfony/security-core/Symfony/Component/Security/Core/Util/StringUtils.php',
    
    'vendor/laravel/framework/src/Illuminate/Support/Facades/Config.php',
    'vendor/psr/log/Psr/Log/AbstractLogger.php',
    'vendor/psr/log/Psr/Log/LogLevel.php',
    'vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Mail/Mailer.php',
    'vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php',
    'vendor/laravel/framework/src/Illuminate/Auth/AuthServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php',
    'vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php',
    //'vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php',
    'vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php',
    'vendor/laravel/framework/src/Illuminate/Support/Facades/HTML.php',
    'vendor/laravel/framework/src/Illuminate/Html/HtmlServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Html/HtmlBuilder.php',
    'vendor/laravel/framework/src/Illuminate/Support/Facades/Response.php',
    'vendor/laravel/framework/src/Illuminate/Support/Facades/Validator.php',
    'vendor/laravel/framework/src/Illuminate/Validation/ValidationServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Validation/Factory.php',
    'vendor/laravel/framework/src/Illuminate/Translation/TranslationServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php',
    'vendor/laravel/framework/src/Illuminate/Translation/LoaderInterface.php',
    'vendor/laravel/framework/src/Illuminate/Translation/Translator.php',
    'vendor/symfony/translation/Symfony/Component/Translation/TranslatorInterface.php',
    'vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php',
    'vendor/laravel/framework/src/Illuminate/Validation/PresenceVerifierInterface.php',
    'vendor/symfony/routing/Symfony/Component/Routing/Route.php',
    'vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php',
    'vendor/symfony/routing/Symfony/Component/Routing/RouteCompilerInterface.php',
    'vendor/symfony/routing/Symfony/Component/Routing/CompiledRoute.php',
    'vendor/laravel/framework/src/Illuminate/Support/Facades/Event.php',
    

	'src/FluentKit/Providers/FluentKitServiceProvider.php',
    
    'vendor/fluentkit/asset/src/FluentKit/Asset/AssetBlueprint.php',
    'vendor/fluentkit/asset/src/FluentKit/Asset/AssetManager.php',
    'vendor/fluentkit/asset/src/FluentKit/Asset/AssetServiceProvider.php',
    'vendor/fluentkit/asset/src/FluentKit/Asset/Facade.php',
    
    'vendor/fluentkit/messages/src/FluentKit/Messages/Messages.php',
    'vendor/fluentkit/messages/src/FluentKit/Messages/MessagesServiceProvider.php',
    'vendor/fluentkit/messages/src/FluentKit/Messages/Facade.php',
    
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/Container.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/Facade.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/Finder.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/Manifest.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/PluginManager.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/PluginServiceProvider.php',
    'vendor/fluentkit/plugin/src/FluentKit/Plugin/ServiceProvider.php',
    
    'vendor/fluentkit/theme/src/FluentKit/Theme/Container.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/Facade.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/Finder.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/Manifest.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/ThemeManager.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/ThemeServiceProvider.php',
    'vendor/fluentkit/theme/src/FluentKit/Theme/FileViewFinder.php',
    
    'vendor/fluentkit/repositories/src/FluentKit/Repositories/AbstractRepository.php',
    'vendor/fluentkit/repositories/src/FluentKit/Repositories/RepositoryInterface.php',
    
    'vendor/fluentkit/supermodel/src/FluentKit/SuperModel/SuperModel.php',
    
    'vendor/fluentkit/user/src/FluentKit/User/UserServiceProvider.php',
    'vendor/fluentkit/user/src/FluentKit/User/Models/User.php',
    'vendor/fluentkit/user/src/FluentKit/User/Repositories/UserRepositoryInterface.php',
    'vendor/fluentkit/user/src/FluentKit/User/Repositories/UserRepository.php',

);