language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - travis_retry find storage -type d -exec chmod 777 {} \;
  - travis_retry find storage -type f -exec chmod 777 {} \;
  - travis_retry cd fluentkit
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true